pragma Singleton

import QtQuick
import Quickshell
import Quickshell.Io

/**
 * KWin port addition: burningb95's hand-picked icons in place of specific
 * Material Symbols. MaterialSymbol asks sourceFor(name) and, when it gets a
 * file back, draws that image at the same size instead of the font glyph.
 *
 * Two kinds of key:
 *  - a Material Symbols name, swapped everywhere it appears. Only names that
 *    mean one thing throughout iNiR are listed.
 *  - a "candy:<id>" name, set explicitly at a call site where the Material
 *    name is too generic to map globally (e.g. "schedule" is mostly a clock,
 *    but on the widget tab it means the timer; "dark_mode" is also the
 *    night marker in clocks, so only the dark-mode toggles opt in).
 *
 * The SVGs live in assets/candy (sources and licenses in its CREDITS.md).
 */
Singleton {
    id: root

    readonly property string dir: Quickshell.shellPath("assets/candy")

    readonly property var files: ({
        "clear-notifications": "clear-notifications.svg",
        "do-not-disturb": "do-not-disturb.svg",
        "dark-mode": "dark-mode.svg",
        "game-mode": "game-mode.svg",
        "calendar": "calendar.svg",
        "calculator": "calculator.svg",
        "search": "search.svg",
        "timer": "timer.svg",
        "todo": "todo.svg"
    })

    readonly property string candyRoot: "/usr/share/icons/candy-icons"

    /**
     * Material name -> "@<pick id>" (a file above) or a path inside
     * candy-icons. Generated by pillbar-extract/candy_map.py, then pruned by
     * hand: delete a line to give that glyph back to Material Symbols.
     * Loaded synchronously so nothing flashes Material first at startup.
     */
    property var materialMap: ({})
    FileView {
        path: `${root.dir}/material-map.json`
        blockLoading: true
        watchChanges: true
        onFileChanged: reload()
        onLoaded: {
            try { root.materialMap = JSON.parse(text()) }
            catch (e) { console.warn("[CandyGlyphs] bad material-map.json:", e); root.materialMap = ({}) }
        }
    }

    function sourceFor(name: string): string {
        const n = String(name ?? "")
        const target = n.startsWith("candy:") ? "@" + n.slice(6) : (root.materialMap[n] ?? "")
        if (target.startsWith("@")) {
            const file = root.files[target.slice(1)]
            return file ? `file://${root.dir}/${file}` : ""
        }
        return target.length > 0 ? `file://${root.candyRoot}/${target}` : ""
    }
}
